[build]
  command="npm run build"
  publish="demo-store-core/packages/website/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = true

[build.environment]
  NEXT_PUBLIC_DATA_FETCHING="ssr"
  NEXT_PUBLIC_CONFIG_FOLDER="../../../config/"
  NEXT_PUBLIC_LOCALES_DATA_FOLDER="../../../data/locales/"

[template.environment]
  NEXT_PUBLIC_JSON_DATA_FOLDER="JSON data folder path"
  SITE_URL="Base url of your website."
  NEXT_PUBLIC_CL_CLIENT_ID="Commerce Layer Sales Channel Client ID."
  NEXT_PUBLIC_CL_ENDPOINT="Commerce Layer Sales Channel Endpoint."
